# pin at 3.2.0 to match puppet.git for now
mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib',
  :ref => '3.2.0'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat.git',
  :ref => '1.1.1'

mod 'git',
  :git => "https://github.com/puppetlabs/puppetlabs-git.git",
  :ref => "0.2.0"

mod 'firewall',
  :git => "https://github.com/puppetlabs/puppetlabs-firewall.git",
  :ref => "0.4.2"
